# Generated by Django 4.1 on 2022-12-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_feature',
            field=models.ManyToManyField(related_name='rooms_feature', to='room.roomfeature'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_small_img',
            field=models.ManyToManyField(related_name='rooms_img', to='room.roomsmallimage', verbose_name='Room Small Image'),
        ),
    ]
