# Generated by Django 4.1 on 2022-12-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_specialoffer_alter_room_room_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('booking_arrival', models.DateField(null=True, verbose_name='Arrival')),
                ('booking_departure', models.DateField(null=True, verbose_name='Departure')),
                ('no_of_guests', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], verbose_name='Number of Guests')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='Room Choice')),
            ],
            options={
                'ordering': ['booking_arrival'],
            },
        ),
        migrations.AddIndex(
            model_name='bookroom',
            index=models.Index(fields=['booking_email'], name='room_bookro_booking_3fc189_idx'),
        ),
        migrations.AddIndex(
            model_name='bookroom',
            index=models.Index(fields=['booking_arrival', 'booking_departure'], name='room_bookro_booking_43c81e_idx'),
        ),
    ]
